### ISSUE TITLE
Symfony 4

### ISSUE THREAD

**Issue by tniemann** [tedious/TedivmStashBundle#107]
Hi,

when will Symfony 4 be supported?

Regards,
Thomas

**Comment by andrerom** [comment]
I'm not speaking for the maintainers , but given Stash is not really activly maintained, there is no plan for that currently as far as I know.

There are also a lot of newer cache libraries out there.

But if (for instance) Symfony Cache is not an option for you, your best bet is to get someone to contribute support for Symfony 4 here.

**Comment by tedivm** [comment]
Stash is actively maintained, but this bundle really isn't. Pull requests are always welcome though.
