### ISSUE TITLE
Set Logger in configuration

### ISSUE THREAD

**Issue by samarties** [tedious/TedivmStashBundle#60]
Hello,

What is the suggested method for injecting a Logger in to a Pool? Would it make sense to add an entry to the cache definition in config.yml which allowed a Logger to be specified for each cache? Something like below?

    stash:
        caches:
            first:
                drivers: [ FileSystem ]
                registerDoctrineAdapter: true
                FileSystem: ~
                logger: logger_service_name
            second:
                drivers: [ Apc, FileSystem ]
                inMemory: false
                FileSystem ~
                logger: another_logger_service_name

**Comment by tedivm** [comment]
That would be a good idea. If you wanted to make a pull request that would be great, otherwise I'll add this to the list and work on it when I've got some more time.

**Comment by samarties** [comment]
Resolved with merge https://github.com/tedious/TedivmStashBundle/pull/61
