### ISSUE TITLE
Triggers deprecation notices in Symfony 2.7

### ISSUE THREAD

**Issue by EvanPurkhiser** [tedious/TedivmStashBundle#66]
In 2.7 symfony triggers `E_USER_DEPRECATION` errors for deprecated functionality.

[Factory service/method](https://github.com/tedious/TedivmStashBundle/blob/e4244e80b44b2182672304d38cbef47a5d44d63d/Resources/config/services.xml#L23-L24) setters are deprecated and should be replaced with:

```xml
<factory service="..." method="..." />
```

This package is BC up to Symfony 2.1 though, so I'm not sure what the right course of action would be.

**Comment by tedivm** [comment]
Closed via #65.
