### ISSUE TITLE
remove deprecated factory-class attribute in Resources/config/services.xml

### ISSUE THREAD

**Issue by digibeuk** [tedious/TedivmStashBundle#68]
With Xdebug scream enabled i see the following deprecation notice

Deprecated: The "factory-class" attribute in file "vendor/tedivm/stash-bundle/DependencyInjection/../Resources/config/services.xml" is deprecated since version 2.6 and will be removed in 3.0. Use the "factory" element instead. in vendor/symfony/symfony/src/Symfony/Component/DependencyInjection/Loader/XmlFileLoader.php on line 154

**Comment by tedivm** [comment]
This should be resolved in the latest release.
