### ISSUE TITLE
v0.5.2 and v0.4.3 releases

### ISSUE THREAD

**Issue by andrerom** [tedious/TedivmStashBundle#80]
Would be great to get releases on 0.5 and 0.4 with #75 `tracking_values` fix in it, in order for us to solve #72.

**Comment by tedivm** [comment]
I'm moving right now and haven't had a chance to resolve this (or other issues). I've added you to this repository so you can make these changes yourself.

**Comment by andrerom** [comment]
> I'm moving right now and haven't had a chance to resolve this (or other issues). 

clear

>I've added you to this repository so you can make these changes yourself.

hmm, can't see any changes *(in what I have access to, or membership to)*.

**Comment by andrerom** [comment]
> hmm, can't see any changes (in what I have access to, or membership to).

ignore, got the email

**Comment by andrerom** [comment]
Solved:
https://github.com/tedious/TedivmStashBundle/releases/tag/v0.5.2
https://github.com/tedious/TedivmStashBundle/releases/tag/v0.4.3
