### ISSUE TITLE
StashBundle not supporting Stash v1.0.0-dev

### ISSUE THREAD

**Issue by layanto** [tedious/TedivmStashBundle#84]
Would like to use StashBundle with PHP7 which would need apcu support added to stash v1.0.0-dev (see https://github.com/tedious/Stash/issues/274). But composer.json of StashBundle only allows using Stash 0.13.*. Is StashBundle not yet compatible with Stash v1.0.0-dev or is this just requiring update to composer.json?

**Comment by tedivm** [comment]
It should just require a change to composer.json.
